### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ArianeMora** [giupardeb/EpiMethEx#2]
Hi I'm trying to install this, running: ``R CMD build EpiMethEx``. I have R version 4.1, running on mac (x86_64-apple-darwin17.0 ) and BiocManager v 1.30.16.  FYI It failed multiple times and requires the following to be installed (and possibly other packages that I already had installed):

```
BiocManager::install("MultiAssayExperiment")
install.packages("miscTools")
install.packages("RcmdrMisc")
install.packages("psych")
```
Would recommend adding required installs to your package so users don't have to install them  i.e. at the top of the script:
```
packages <- c("miscTools", "RcmdrMisc", "psych")
install.packages(setdiff(packages, rownames(installed.packages())))
```
Anyway following installing the required packages I got the error:
```
* checking for file ‘EpiMethEx/DESCRIPTION’ ... OK
* preparing ‘EpiMethEx’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building ‘epimethex_analysis.Rmd’ using rmarkdown
Warning in xtfrm.data.frame(x) : cannot xtfrm data frames
Warning in xtfrm.data.frame(x) : cannot xtfrm data frames
Warning in xtfrm.data.frame(x) : cannot xtfrm data frames
Warning in `[<-.factor`(`*tmp*`, ri, value = -1.859692469761) :
  invalid factor level, NA generated
Warning in `[<-.factor`(`*tmp*`, ri, value = -0.396742484881) :
  invalid factor level, NA generated
Warning in `[<-.factor`(`*tmp*`, ri, value = 0.225157530238) :
  invalid factor level, NA generated
Quitting from lines 44-80 (epimethex_analysis.Rmd)
Error: processing vignette 'epimethex_analysis.Rmd' failed with diagnostics:
task 1 failed - "undefined columns selected"
--- failed re-building ‘epimethex_analysis.Rmd’

SUMMARY: processing the following file failed:
  ‘epimethex_analysis.Rmd’

Error: Vignette re-building failed.
Execution halted
```
Do you have a pre-built version I can install? Otherwise please let me know if you update the code with the error resolved or if this is no longer under development, cheers!

**Comment by giupardeb** [comment]
Hi, thanks a lot to report the issue. Unfortunately I don't have a pre-built version. The tool was tested with R: v3.4.4(how can you see on the README) and with the last version of R (4.1) there are some problems with dependencies of the packages (i.e "MultiAssayExperiment", "SummarizedExperiment", "GenomicRanges", etc..). So, at the moment I can't maintain the tool, but if you have a time to fix these problems, any PR will be appreciated.

**Comment by ArianeMora** [comment]
No worries thanks for letting me know!
